### ISSUE TITLE
Nutzbare Version (v2) -- Eingabemaske für das Verfassen von Allgemeinen Meldungen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#14]
Eine Eingabemaske soll als "Overlay" erscheinen, wenn ein Nutzer eine allgemeine Meldung verfassen möchte. Dazu soll er auf einen Button "Meldung schreiben" (nur ein vorläufiger Name) klicken.

(siehe auch: http://www.queness.com/resources/html/modal/jquery-modal-window.html)
In Browsern, die kein Javascript unterstützen, soll man beim Klicken auf den Button auf eine andere Seite (mit Eingabefeld) umgeleitet werden.

 @Antasio, @ATL4s789

**Comment by switchhax** [comment]
"Eine [...] erschenen (sic!)[,] wenn [...] möchte."
"In Browsern[,] die [...] unterstützen[,] soll [...] werden.

**Comment by Quwert** [comment]
Das Overlay vielleicht nicht,
aber: Das Bestehende so anpassen, dass es "gut" aussieht.
