### ISSUE TITLE
Nutzbare Version (v2) -- Umlaute durch HTML &xuml; ersetzen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#15]
Beim Bereitstellen der Meldungen sollena lle Umlaute + Sonderzeichen durch &xuml; Sequenzen ersetzt werden.

**Comment by switchhax** [comment]
"seuenzen" what?

**Comment by Quwert** [comment]
Anscheinend ist das nicht nötig (UTF-8 ist im HTML-header gesetzt)

**Comment by switchhax** [comment]
*sollen alle  
Was auch immer "seqenzen" sind.
