### ISSUE TITLE
Nutzbare Version (v2) -- Nur die Neuesten 10 Meldungen laden

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#16]
Beim ersten Aufruf sollen nur die neuesten 10 Meldungen geladen werden.
Zusätzlich soll ein "weiter"-Knopf weitere Meldungen anzeigen.

@Quwert, @ATL4s789

**Comment by Quwert** [comment]
Die Anzahl lässt sich ja später noch verändern

**Comment by switchhax** [comment]
Wer isn bitte der Qwert, denn du markiert hast? Hamma nen neuen Mitarbeiter?
