### ISSUE TITLE
Nutzbare Version (v3) -- Eingabemaske für neue Nachrichten überprüfen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#17]
Es soll geprüft werden, ob die Eingabefelder (Titel, Meldung) für eine neue Meldung mehr als 2 Zeichen beinhalten.
(Javascript)

@Antasio, @ATL4s789, @switchhax

**Comment by rubenm-AR14** [comment]
Comrade i´ll do this too :)

**Comment by rubenm-AR14** [comment]
Markus, hat du jetzt irgendwie mein Programmcode eingebaut, sodass dieser Issue jetzt geschlossen werden kann?

**Comment by Quwert** [comment]
Noch nicht, Vertretungsplan ist im Moment wichtiger.

**Comment by Quwert** [comment]
Ich baue es bald ein.

**Comment by Quwert** [comment]
In

02c3e09f9b09f775930676bbe6d9c771bad90ede
dd22e49369ffdfe74b1e303d95d6001782e5c789
und
39df68c8c628c4db45de650b7a103c38086c5174

umgesetzt.
