### ISSUE TITLE
Nutzbare Version (v2) -- Browser cache verhindert korrektes Ausloggen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#18]
Wenn man (z.B. in Firefox) den Logout-Button anklickt, findet in manchen Fällen kein Aufruf des serverseitigen Programms statt, sondern man wird sofort auf die Login-Seite umgeleitet, als ob man sich ausgeloggt hätte.

@Antasio, @ATL4s789, @Quwert, @switchhax

**Comment by rubenm-AR14** [comment]
Irgendwie hast du es nicht so mit der Kommasetzung bei Konditionalsätze :D

**Comment by Quwert** [comment]
(,,,,,,,,,,,,,) <-- Hier ein paar Kommata. Bitte verteile diese entsprechend!

**Comment by rubenm-AR14** [comment]
"Wenn [...] anklickt, findet [...] hätte." *Fällen

**Comment by Quwert** [comment]
Anscheinend nützt
`Cache-Control: no-store, no-cache, must-revalidate, max-age=0`
im HTTP-Header bei folgenden Browsern: `Firefox (Windows, Linux), Opera (Android), Internet Explorer 11 (Windows), Epiphany (Linux)`.
Bei `Dillo (Linux)` wird das Logout-Programm durch aggressives Cache-Management anscheinend nicht ausgeführt.
