### ISSUE TITLE
Nutzbare Version (v3) -- Passwort-Stärke-Anzeige einbauen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#19]
Eine Anzeige für die Stärke des Passwortes bei der Registrierung einbauen.
(z.B. durch bunten Balken unter dem Passwort-Feld)

@Antasio, @switchhax

**Comment by rubenm-AR14** [comment]
Aus Spaß wurde Ernst und Ernst ist jetzt 7 Jahre alt.

**Comment by rubenm-AR14** [comment]
Done with JS! @Quwert , bitte mergen nach nochmaligem Anschauen.

**Comment by Quwert** [comment]
ok
