### ISSUE TITLE
git clone PROJEKT + html-Dateien öffnen

### ISSUE THREAD

**Issue by rubenm-AR14** [EGFGy/ISS#21]
Clonet mal das Projekt, geht in den Unterordner `v3/html` jetzt auf `index.html`. Sieht fubar aus. Ist das Absicht?

**Comment by Quwert** [comment]
http://www.motive.co.nz/glossary/linking.php?ref#root

**Comment by rubenm-AR14** [comment]
Also einfach fast überall einen Punkt vor den Slash.

**Comment by Quwert** [comment]
Das brauchst du nur wenn du es lokal editieren willst. Auf dem Server ist es nicht nötig, zudem will ich, dass z.B. die CSS-Referenzen vom root-Verzeichnis ausgehen.
Du brauchst ja eh den Server + fcgiwrapper um die Programme auszuführen.

**Comment by rubenm-AR14** [comment]
Gibts das auch um es zuhause auszutesten, ein Skript vielleicht?

**Comment by Quwert** [comment]
Es gibt eine Anleitung + Nötige Dateien (https://github.com/EGFGy/ISS/blob/master/v3/Installation)

**Comment by rubenm-AR14** [comment]
Danke dir :)

**Comment by Quwert** [comment]
gehts?

**Comment by rubenm-AR14** [comment]
Ich bastel morgen dran, grade leider keine Zeit, muss meine cholinergen Synapsen füttern :P

**Comment by rubenm-AR14** [comment]
Unter besagter IP-Adresse des Skriptes lässt sich kein Server erreichen und das mit der Datenbank funzt net. Ebenfalls wie genau kompilier ich die Programme?

**Comment by Quwert** [comment]
Hast du curl installiert? (für server-ip ...) (Was meinst du mit "Unter besagter IP-Adresse[...]" ?)
Was funktioniert mit der Datenbank nicht?
Zum Kompilieren der Programme brauchst du Codeblocks oder ein Makefile.

**Comment by rubenm-AR14** [comment]
Keine Ahnung. Es gibt einen Output in der Datei. Die IP funzt net.
Die 2 Befehle funzen nicht.
Und wie weiter beim kompilieren?

**Comment by Quwert** [comment]
Meinst du "checkip.dyndns.org"?
Ich bin gerade dabei ein Makefile zu erstellen.

**Comment by Quwert** [comment]
Es wäre gut wenn alle mal die [Installationsanleitung](https://github.com/EGFGy/ISS/blob/master/v3/Installation) durchlesen, ausprobieren und evtl. auftretende Probleme hier oder in einer neuen Issue beschreiben.

Dabei bitte folgende Datei beachten: https://github.com/EGFGy/ISS/blob/master/Allgemeine_Testprozedur

@switchhax @Antasio @ATL4s789 @Quwert

**Comment by rubenm-AR14** [comment]
Ich probiers morgen nochmal.
