### ISSUE TITLE
Nutzbare Version (v3) -- Bestätigungsmail oder Captcha?

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#22]
Soll auf der Seite ein Captcha eingeblendet werden?
ODER
Soll dem Nutzer nach der Registrierung eine E-Mail zugesandt werden, in der ein Bestätigungsslink enthalten ist, der bei Aufruf das Benutzerkonto der Person aktiviert?

Man Könnte auch das Captcha als Anhang in der Mail schicken (der Nutzer müsste dann nur noch auf einer "Aktivierungs-Seite" seine E-Mail-Adresse / Kürzel und das Wort in dem Captcha eingeben um das Konto zu aktivieren?

@ATL4s789, @Quwert, @Antasio, @switchhax

**Comment by ATL4s789** [comment]
Also ich bin für die Bestägigungsmail, weil Niemand mag CAPTCHAs, und die CAPTCHAs mit der E-Mail zu kombinieren klingt für mich zu umständlich für den Endnutzer.
Wir müssen es ja schließlich nicht übertreiben.

**Comment by rubenm-AR14** [comment]
:+1:

**Comment by Quwert** [comment]
Ok, dann wird es mit einem "Bestätigungslink" durchgeführt.
