### ISSUE TITLE
Nutzbare Version (v3) -- Konzept für das Speichern von Vertretungsstunden

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#24]
Das Speichern von Vertretungsstunden könnte ähnlich wie das von (festen) Kursen aufgebaut sein.

<pre>
id | name | zeit | raum | lehrer
id:       Wie in Kurse, die ID des Eintrages !! NICHT die des Kurses !!
name:     Kursname
zeit:     Zeit zu der der Kurs (eigentlich) stattfindet (Aus Spalte: "Std.")
zeit_neu: Neue Zeit des Kurses
raum:     Raum in dem der Kurs stattfindet
lehrer:   Vertretungslehrer (nur dann gefüllt wenn auch ein anderer Lehrer die Stunde hält)
</pre>

Andere Vorschläge?

**Comment by switchhax** [comment]
Nö!

**Comment by Quwert** [comment]
Wir könnte das jetzt erstmal so umsetzten. Es ist wahrscheinlich, dass das später nochmal geändert wird.

<pre>
id | name | v_zeit | v_raum | v_lehrer
id:       Wie in Kurse, die ID des Eintrages !! NICHT die des Kurses !!
name:     Kursname
v_zeit:   Neue Zeit des Kurses (NULL wenn keine Änderung stattfindet)
v_raum:   Raum in dem der Kurs stattfindet (NULL wenn keine Änderung stattfindet)
v_lehrer: Vertretungslehrer (nur dann gefüllt wenn auch ein anderer Lehrer die Stunde hält NULL wenn keine Änderung stattfindet)
</pre>

**Comment by rubenm-AR14** [comment]
Why not?
klasse,std,vertretung,fach,raum,statt,lehrer
