### ISSUE TITLE
Nutzbare Version (v3) -- Mehrfachbelegung verhindern

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#25]
Verhindern, dass mehrere Kurse die zur gleichen Zeit stattfinden belegt werden und dass mehr als ein Lehrer einen Kurs unterrichtet.
(bei der Kursauswahl)

Vorschlag + Frage: 
Ist es eine gute Idee der Kurstabelle (der Datenbank) eine Spalte hinzuzufügen, die die ID des Lehrers enthält, der diese Stunde hält?

**Comment by rubenm-AR14** [comment]
Vorausgesetzt, der Schüler ist so inkompetent, dass er nicht weiß, ja.

**Comment by Quwert** [comment]
Lösung siehe:
https://github.com/EGFGy/ISS/commit/8b0cc3b4b971241a04925f7614bf17cc9670e04a

Bitte aktuelle Version ausprobieren!!

Es geht vielleicht auch besser.

**Comment by ATL4s789** [comment]
Man könnte den Befehl COUNT(zeit) und dazu noch GROUP BY(zeit) verwenden, um festzustellen welche Kurse sich überschneiden.
Zum Beispiel so: <pre>SELECT zeit, COUNT(zeit) FROM Kurse WHERE name='2D2' OR  name='2E3' OR  name='2E5' OR  name='2G2' OR  name='2INF' OR  name='2K4' OR  name='2KU1' OR  name='2M2' OR  name='2PH1' OR  name='2PHO' OR  name='2P_INF' OR  name='2SK2' OR  name='2SPO1' OR  name='2WR1' OR  name='2W_M' GROUP BY zeit;</pre>

**Comment by Quwert** [comment]
Das ist eine gute Idee :+1: 
Man könnte die Kurse auch noch einzeln durchgehen um dem Nutzer zu sagen, in welchen Stunden er Kurse doppelt hat.

**Comment by ATL4s789** [comment]
:+1:

**Comment by Quwert** [comment]
Wurde anders umgesetzt. Bitte anschauen und testen.

**Comment by Quwert** [comment]
Ich schließe das hier jetzt mal.
Wenn jemand einen Fehler bei dem Programm feststellt --> wieder öffnen + Fehlerbild beschreiben!
