### ISSUE TITLE
Nutzbare Version (v3) -- Komfortfunktion bei den Einstellungen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#28]
Im Bereich der Kursauswahl in den Einstellungen soll es möglich sein, eine komplette Klasse auf einmal auszuwählen, d.h. jemand der z.B. die Klasse 10c besucht soll die Möglichkeit haben alle Kurse, die er sowieso besucht auf einmal auszuwählen und nur noch zwischen unterschiedlichen Sprachen (F, L, SPS), Konfessionen (ETH, K, EV) und Sportgruppen (SW, SM) wählen zu müssen.

Das alles könnte mit Javascript umgesetzt werden.

@Antasio 
(Es macht nichts, dass das dann natürlich in nicht-Javascript-fähigen Browsern nicht funktioniert, es ist ja auch eine "Komfortfunktion")

**Comment by Quwert** [comment]
Ich hab da ein bisschen schon gemacht, das müsste noch verbessert werden.

**Comment by ghost** [comment]
Filter funktionieren jetzt gut, Pflichtfächer werden auch ausgewählt @Quwert
