### ISSUE TITLE
Nutzbare Version (v3)  --  A/B-Wochenrythmus

### ISSUE THREAD

**Issue by ATL4s789** [EGFGy/ISS#29]
Je nach Woche wechselt sich der Stundenplan. Zum korrekten Anzeigen der Stunden im Stundenplan wird deshalb noch der schulinterne A/B-Wochenrythmus benötigt.
Dieses Problem tritt beispielsweise bei den Seminaren in der Oberstufe oder bei den Intensivierungsstunden der Unterstufen auf.

**Comment by Quwert** [comment]
Beispiel für das Format:
`Mo9A` <-- Diese Stunde findet nur am Montag einer A-Woche statt

**Comment by Quwert** [comment]
Wir könnten die Umsetzung davon noch ein bisschen nach hinten verschieben.
Es gibt noch viele andere Dinge (Doppelbelegung, Aktivierungsmail, usw.).

**Comment by Quwert** [comment]
Das wird vorerst mal abgebrochen!
