### ISSUE TITLE
Nutzbare Version (v3) -- Passwortänderung

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#30]
Zu den Einstellungen ein Eingabefeld hinzufügen und eine Verarbeitungsmöglichkeit für eine Passwortänderung einbauen.
in `v3/C/backend/settings.c`

**Comment by ATL4s789** [comment]
Eingebaut, Funktionen durch C-Programm fehlen aber noch.
https://github.com/EGFGy/ISS/blob/master/v3/Vorschlaege/Passwort-Aenderung.html
@Quwert

**Comment by Quwert** [comment]
Funktionalität ist da!
Muss aber Noch getestet werden!

**Comment by ghost** [comment]
Ich kümmer mich drum.

**Comment by ghost** [comment]
@Quwert Hat bei mir alles funktioniert
