### ISSUE TITLE
-unbestimmt- -- Eine Startseite erstellen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#32]
Man könnte zur besseren Verständlichkeit für außenstehende Personen eine Startseite erstellen, auf der alle wichtigen Fakten zu diesem Projekt kurz genannt und alles ein bisschen erklärt wird.
Es muss nichts großes sein. Damit es schnell geht (und da diese Gebiet auch nicht unsere Hauptaufgabe ist) könnte man das Design von http://purecss.io/layouts/marketing/ übernehmen.

**Comment by ghost** [comment]
Ich kümmer mich drum, versuchs dieses Wochenende hinzukriegen

**Comment by Quwert** [comment]
:+1: ok

**Comment by ghost** [comment]
@Quwert  Kannst du mir ein paar Screenshots der verschiedenen Seiten zukommen lassen? Am besten per Email, ich würde gerne ein bis drei davon in die Startseite integrieren (Auswahl der Fächer, Stundenplan, Menü)

**Comment by Quwert** [comment]
ja

**Comment by Quwert** [comment]
kannst du 7z öffnen?

**Comment by ghost** [comment]
@Quwert Startseite ist fertig und Pullrequest steht. Alle dependencies innerhalb des Codes sind jetzt auf das Github-Repository angepasst, die Bilder müssen noch unter ISS/v3/html/img eingefügt werden, habe keine Ahnung wie das gehen soll :)

**Comment by Quwert** [comment]
Die sollten wir nicht unbedingt in dem Repo Speichern

**Comment by Quwert** [comment]
Sieht super aus!
Ich pass das mit den Bildern + Verlinkungen jetzt noch an.

**Comment by Quwert** [comment]
Ich hab die Startseite jetzt auch entsprechend in die index.html verschoben.

**Comment by Quwert** [comment]
Das Einzige was man noch verbessern könnte wäre der Kontrast im zweiten Abschnitt (Dunkelgrau auf etwas weniger Dunkelgrau ist jetzt nicht so toll zu lesen (v.A. für ältere Leute, oder auf dem Handy im Sonnenlicht). Dasselbe gilt für den Türkisen Text unten auf wem Grund (man könnte ihn ja etwas blauer machen)
