### ISSUE TITLE
Lizenzproblem!

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#39]
Auf der Seite werden mehrere Bilder von www.icons8.com eingebunden.
Diese stehen unter folgender Lizenz: https://creativecommons.org/licenses/by-nd/3.0/
`--> Wir dürfen sie nicht verändern (z.B. Farben anpassen)`

Da aber genau das (Farben anpassen(invertieren + Transparenz)) für uns nötig ist, müssen wir uns was anders einfallen lassen!

**Comment by ATL4s789** [comment]
Hab nachgeschaut, Farben verändern (also auch invertieren und Transparenz) ist laut deren FAQ erlaubt.

siehe
http://buzz.icons8.com/knowledgebase/articles/293782-may-i-change-the-size-or-color-of-the-free-icons
