### ISSUE TITLE
Kurzbeschreibung des Projekts für JugendForscht

### ISSUE THREAD

**Issue by ATL4s789** [EGFGy/ISS#40]
Ich habe mal einen ersten Entwurf für eine Kurzbeschreibung erstellt.
Hinterlasst gerne Kritik falls technische Aspekte falsch beschrieben wurden oder formale Ungereimtheiten auffallen.

---

Im Zuge unseres P-Seminars Informatik „Softwarearchitektur“ entschlossen wir uns ein Infoportal für Schüler und Lehrer zu erstellen. Ein grundlegender Gedanke war die Zusammenführung des Vertretungsplans mit den Stundenplänen der Schüler, sowie das Verteilen von Meldungen, wie Ankündigungen oder Hausaufgaben.
Schnell kamen wir überein bei den Meldungen zwischen allgemeinen und kursbezogenen Meldungen zu unterscheiden. Meldungen können im Portal nur von Lehrern erstellt werden. Kursbezogene Nachrichten können für mehrere Kurse eines Lehrers gleichzeitig angezeigt werden.
Da sowohl Schüler als auch Lehrer Kurse (bestimmtes Unterrichtsfach in einer bestimmten Klasse) besuchen, werden diese zusammenfassend als Person bezeichnet, wodurch sie die Funktionen des Infoportals gleichwertig benutzen können. Im Einstellungsbereich kann die Person die Kurse auswählen, die sie besucht, und mittels einer Filterfunktion wird die Auswahl der entsprechenden Kurse für die jeweilige Jahrgangsstufe angepasst. Ebenfalls ist es dort möglich das Passwort sowie die E-Mail-Adresse zu ändern.
Der Stundenplan wird auf der Seite in Form einer Tabelle dargestellt und ergibt sich aus den Angaben, die im Einstellungsbereich gemacht wurden. Für jeden Kurs, den man auswählt sind bestimmte Datensätze in einer Datenbank vorhanden. Dort steht für den jeweiligen Kurs sowohl seine Bezeichnung aus der sich das Fach sowie die Jahrgangsstufe bzw. spezifische Klasse bestimmen lassen, der Wochentag, als die Stunde und der Raum in dem er stattfindet. Ein Kurs kann stets von nur einem Lehrer besucht werden, dieser wird dann auch in dem Stundenplan des Schülers angezeigt, obwohl er nicht im jeweiligen Kurs gespeichert ist. Dies ermöglicht eine dynamische Lehrerzuweisung zu den Kursen, sollte ein Lehrer beispielsweise in Vater-/Mutterschaftsurlaub gehen und somit einen langfristigen Lehrerwechsel notwendig machen. Im nächsten Schritt zur Erstellung des persönlichen Stundenplans wird der Vertretungsplan, der auf der Schulwebsite einzusehen ist, in der Stundenplan des Schülers integriert. Es wird überprüft, ob im Vertretungsplan Kurse enthalten sind, die der Schüler auch besucht und die spezifische Stunde wird dann im Stundenplan des Schülers ausgebessert sowie farbig markiert, um auf die Änderung aufmerksam zu machen. So wird im Falle einer Vertretung das eigentliche Lehrerkürzel durch das des Vertretungslehrers ersetzt und grün markiert. Entfällt die Stunde wird der Text durchgestrichen und das Feld rot markiert. Dies gilt analog für Raumänderungen und ist auch kombinierbar. Der Wochenrhythmus unserer Schule in A- und B-Wochen wird ebenfalls beachtet. Dieser ist sowohl bei den Intensivierungsstunden der Unterstufe wie auch bei den Seminaren der Oberstufe von Bedeutung.
Unser Registrierverfahren verlangt nur nach den notwendigen Daten, also den Namen, Vornamen und die E-Mail-Adresse, um mit Schülern in Kontakt treten zu können. Eine Anzeige für die Stärke des Passworts ist eingebaut, um vor allem die jüngeren Schüler zu schützen. Die Hashwerte der Passwörter werden in der Datenbank gespeichert und auch von der Website per HTTPS verschlüsselt übertragen.

**Comment by ATL4s789** [comment]
Hab das jetzt mal in https://github.com/EGFGy/ISS/blob/master/v3/Vorschlaege/Kurzbeschreibung.txt
hochgeladen, damit ihr es auch editieren könnt.

**Comment by switchhax** [comment]
Inwiefern hat euer Projekt mit JugendForscht zu tun, ist doch eher was für JugendHackt nich?

**Comment by rubenm-AR14** [comment]
Weiss nicht, was gut ist oder nicht, also such dir selbst raus.
- E-Mail-Adresse oder Mailadresse

Text erzeugt vielleicht eine Frage:
 Wieso keine Kommentarfunktion? Eine Begründung wäre Nietzsche.

Folgenden Satz würde ich umschreiben:

> Da sowohl Schüler als auch Lehrer Kurse (bestimmtes Unterrichtsfach in einer bestimmten Klasse) 
>  besuchen, werden diese zusammenfassend als Person bezeichnet, wodurch sie die Funktionen des 
> Infoportals gleichwertig benutzen können, nur der Lehrer hat mehr Rechte.

Könnte eventuell eingespart werden (Ein bisschen Captain Obvious):

> , die sie besucht, also die Fächer, die ein Lehrer unterrichtet bzw. die ein Schüler besucht.

Statt `... für die jeweilige Jahrgangsstufe vereinfacht ...` eher `... für die jeweilige Jahrgangsstufe angepasst...`.

`... Kurs den man auswählt sind ...` Relativsatz! Kommatas wären ebenfalls Nietzsche.

> Dort steht für den jeweiligen Kurs seine Bezeichnung aus der sich das Fach sowie die Jahrgangsstufe 
> bzw. spezifische Klasse bestimmen lassen, der Wochentag, die Stunde und der Raum in dem er 
> stattfindet.
> Sowohl-als-auch-Konstruktion?

`... besucht, also unterrichtet, ...` Dopplung machen zwar verständlicher, aber auch unübersichtlicher.

`somit einen langfristigen Lehrerwechsel erzwingen.` Ein bisschen weniger brutal?!

`Es wird überprüft ob im` Komma? Wegen adverbialem Nebensatz.

`Raumtäusche` ?!

`, also den Namen, Vorname und die E-mail-Adresse,` Klingt komisch?

`gewährleistet und die Passwörter werden` Und streichen!

**Comment by rubenm-AR14** [comment]
Wird die Kritik auch mal wahrgenommen?

**Comment by Quwert** [comment]
Änderungen Eingebaut + bei jufo hochgeladen
