### ISSUE TITLE
Nutzbare Version (v3) -- Einstellungen

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#42]
Reset-Knopf für das Suchformular hinzufügen (Javascript)

**Comment by ghost** [comment]
gesehen, mach ich dann morgen im Seminar

**Comment by Quwert** [comment]
ok
bring dein Laptop mit

**Comment by ghost** [comment]
@Quwert 
@ATL4s789 Funktionalität ist da, vlt. noch neben/in die Tabelle integrieren.

**Comment by rubenm-AR14** [comment]
#43 ?
