### ISSUE TITLE
Auffälligkeiten

### ISSUE THREAD

**Issue by rubenm-AR14** [EGFGy/ISS#47]
Startseite:
- [x] "Erfahre mehr" scheint nicht sehr nutzvoll
- [x] Anmeldung und Registrierung doppelt

Fehler auf der Hilfeseite:
- [x] Rechtsschreibung bei Passwortüberprüfung
- [x] Inhalt?!

Registrierung:
- [x] Passwortprüfung funzt nicht

Kurzbezogenes:
- [x] Was macht die "Quelle der Icons" hier?

Einstellung
- [x] Passwortstärke funzt nich
- [ ] Stundenplan funzt nicht

**Comment by Quwert** [comment]
Quelle der Icons --> https://icons8.com/license/
Man muss die Verlinkung einbauen. (aber nicht unbedingt auf jeder Seite, oder? Rechtliche Frage?)

**Comment by Quwert** [comment]
@switchhax, Was geht bei der Passwortstärke (bei den Einstellungen) / Passwortprüfung (bie der Registrierung) nicht?

**Comment by Quwert** [comment]
Ok, selber gefunden:
--> Lösung 21265d48aecc44f4abc80e18f3e0e35d2b31d0f0

**Comment by ATL4s789** [comment]
zu:
Fehler auf der Hilfeseite:
- Inhalt?!"

Ruben, könntest du da was schreiben?

**Comment by Quwert** [comment]
"Stundenplan funzt nicht"
ist damit gemeint, dass der aktuelle Stundenplan nicht eingebaut ist, oder geht was anderes nicht?

**Comment by rubenm-AR14** [comment]
Bei dem Stundenplan funktioniert die Anzeige von Raumtäuschen und Stundenausfall (sowie auch von Haarausfall) nicht.
