### ISSUE TITLE
Skript für PDF-extrahierung

### ISSUE THREAD

**Issue by Quwert** [EGFGy/ISS#6]
Ein Skrip schreiben um die Namen der Lehrer  und deren Kürzel aus der Kürzelliste zu extrahieren und in die Datenbank einzutragen.

**Comment by rubenm-AR14** [comment]
Datenbank-Konfiguartionen/Modellierungen? Zur Simulation auf meinem Rechner.

**Comment by Quwert** [comment]
sudo apt-get install mysql-server mysql-client
Datenbank aus der Schule habe ich dir per E-mail geschickt.

**Comment by rubenm-AR14** [comment]
:+1:

**Comment by rubenm-AR14** [comment]
In welcher Sprache, da es ein Skript sein muss, gehts ja net in Java.

**Comment by rubenm-AR14** [comment]
Was tust du?!
